### PR TITLE
Fix/centrdataconc

### PR DESCRIPTION
**Pull request by samartse**
Some bugfixing.

### CODE REVIEW

**Review by BenMoon — COMMENTED** [review]
Can you please add some information (e.g. to the commit message), as to why this is not required any longer?

**Review by BenMoon — COMMENTED** [review]
This part of the code is called rather often. I think unless we know, that `try/catch` is more or less performant than an `if`, please leave the TODO comment in there.
It would be absolutely fantastic, if you could think of a test which would cover this part for the future.

**Comment by samartse** [comment]
The try catch called approximately 100-200 times during complete processing. Therefore, I would say it has no overhead.
It seems to me, that the try-catch block was set because of the bug. 
The point is, that the code could work under certain condition - when chunk was containing only one trigger data, or when two trigger data had the same number of voxels (what is less probable).

**Comment by samartse** [comment]
Try/catch section removed, None data is filtered during building up the list from map object. It must be certainly faster.

**Comment by BenMoon** [comment]
Fix problem empty centroiding lists

**Pull request merged**
